# On récupère une image Nginx basée sur Alpine Linux
FROM nginx:alpine

# On copie la configuration Nginx sur notre conteneur
COPY nginx.conf /etc/nginx/nginx.conf

# On expose le port 80 et 443
EXPOSE 80 443
